name: Validate Production Pull Request

on:
  push:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Install SFDX
          run: |
            npm install --global sfdx-cli
            sfdx --version
            
        - name: Login To Org
          run: |
            echo "running sfdx login using sfdx-url"
            sfdx org login sfdx-url --set-default --sfdx-url-file <(echo "${{ secrets.SFDX_AUTH_URL }}")

        - name: Retrive Account records via soql
          run: |
            echo "running Retrive Account records via soql start"
            sfdx force:data:soql:query -q "SELECT Id, Name FROM Account LIMIT 1"
            echo "running Retrive Account records via soql end"
        - name: Retrieve Account Record
          run: |
            echo "Retrieving Account record"
            sfdx force:data:record:get -s Account -i '0015i00000fQe8pAAC' -u creative-impala --json
        - name: Print Account Record
          run: |
            echo "Printing Account record"
            echo ${{ steps.retrieve-account.outputs.result }}
