name: Validate Production Pull Request

on:
  pull_request:
    branches:
      - main
    paths:
      - 'force-app/**'
jobs:
  validate:
    runs-on: ubuntu-latest
    environment: test
    steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Login To Org
          run: |
            echo "running sfdx login using sfdx-url"
            sfdx org login sfdx-url --set-default --sfdx-url-file <(echo "${{ secrets.SFDX_AUTH_URL }}")
        - name: Retrieve Account Record
          run: |
            echo "Retrieving Account record"
            sfdx force:data:record:get -s Account -i '0015i00000fQe8pAAC' -u creative-impala --json
        - name: Print Account Record
          run: |
            echo "Printing Account record"
            echo ${{ steps.retrieve-account.outputs.result }}

