name: Validate Production Pull Request

on:
  push:
    branches:
      - main
    paths:
      - 'force-app/**'
jobs:
  validate:
    runs-on: ubuntu-latest
    environment: test
    steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Login To Org
          run: |
            echo "running sfdx login using sfdx-url"
            sf org login web --instance-url https://creative-impala-3wf91c-dev-ed.trailblaze.lightning.force.com/ --set-default --browser chrome --client-id 3MVG9wt4IL4O5wvKdLFBIlo07OoVWmvx2r8ZAwNFtJU6Z6RJfQwGI.e_Gj8L7PFPzzKfgoca2kRppmkYHpfeC
        - name: Retrieve Account Record
          run: |
            echo "Retrieving Account record"
            sfdx force:data:record:get -s Account -i '0015i00000fQe8pAAC' -u creative-impala --json
        - name: Print Account Record
          run: |
            echo "Printing Account record"
            echo ${{ steps.retrieve-account.outputs.result }}

    
