name: Validate Production Pull Request

on:
  pull_request:
    branches:
      - master
    paths:
      - 'force-app/**'
jobs:
  validate:
    runs-on: ubuntu-latest
    environment: test
    steps:
        - uses: actions/checkout@v3
        - name: Validate on Production
          uses: akshaymakwana-cloobees/devopstest
          with:
            SFDX_AUTH_URL: ${{secrets.SFDX_AUTH_URL}}
            DRY RUN: true